In [5]:
import pandas as pd
movies = pd.read_csv("movies_with_emotions.csv")
big_data = pd.read_csv("D:/Downloads/TMDB_movie_dataset_v11.csv")

In [19]:
merged = movies.merge(big_data[["title", "backdrop_path"]], on=["title"], how="left")
merged

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,release_year,tagged_overview,simple_genres,joy,anger,sadness,fear,disgust,surprise,backdrop_path
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,1994,278 Framed in the 1940s for the double murder ...,Fiction,0.635536,0.739559,0.051363,0.040564,0.549477,0.119869,/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg
1,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,1994,278 Framed in the 1940s for the double murder ...,Fiction,0.635536,0.739559,0.051363,0.040564,0.549477,0.119869,NaN
2,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,1995,"19404 Raj is a rich, carefree, happy-go-lucky ...",Non Fiction,0.631513,0.176186,0.104756,0.823338,0.809544,0.676329,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg
3,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,1972,"238 Spanning the years 1945 to 1955, a chronic...",Fiction,0.963215,0.104007,0.051363,0.040564,0.850916,0.111690,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg
4,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,1972,"238 Spanning the years 1945 to 1955, a chronic...",Fiction,0.963215,0.104007,0.051363,0.040564,0.850916,0.111690,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24146,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,2019,455957 Seeking justice for his partner’s murde...,Fiction,0.261567,0.618782,0.051363,0.040564,0.549477,0.111690,NaN
24147,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,2019,455957 Seeking justice for his partner’s murde...,Fiction,0.261567,0.618782,0.051363,0.040564,0.549477,0.111690,NaN
24148,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,2019,455957 Seeking justice for his partner’s murde...,Fiction,0.261567,0.618782,0.051363,0.040564,0.549477,0.111690,NaN
24149,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,2019,455957 Seeking justice for his partner’s murde...,Fiction,0.261567,0.618782,0.051363,0.040564,0.549477,0.111690,NaN
24150,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,2019,455957 Seeking justice for his partner’s murde...,Fiction,0.261567,0.618782,0.051363,0.040564,0.549477,0.111690,NaN

In [21]:
merged = merged.drop_duplicates(subset="id", keep="first")
merged

backdrop_path
False    6176
True       58
Name: count, dtype: int64

In [24]:
movies = merged.rename(columns={"backdrop_path": "poster"})
movies.to_csv("movies_with_posters.csv", index=False)

In [31]:
movies[movies["title"] == "Your Name."]

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,release_year,tagged_overview,simple_genres,joy,anger,sadness,fear,disgust,surprise,poster
9,372058,Your Name.,"Romance,Animation,Drama",ja,High schoolers Mitsuha and Taki are complete s...,158.27,2016-08-26,8.5,8895,2016,372058 High schoolers Mitsuha and Taki are com...,Non Fiction,0.064134,0.104007,0.051363,0.040564,0.917949,0.11169,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg